### ISSUE TITLE
Raspberry zero wh - kernel module problem

### ISSUE THREAD

**Issue by jmfoucher** [jdonald/uvc-gadget#1]
Hello,

thanks for all the patches. I am trying to turn my raspberry pi zeroWH with a pinoir (1.3 or 2.1) or a spycam to a uvc camera .

$ uname -a
Linux raspberrypi 4.9.80+ #1098 Fri Mar 9 18:51:28 GMT 2018 armv6l GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch

raspberry kernel commit :
a2f34d45809d8685bca1e91989e35746499ac400

This is the command line launched most of the time for the tests :
$ ./uvc-gadget -b -s 2 -m 1 -v /dev/video0 -u /dev/video1

There is a problem with drivers/usb/gadget/function/uvc_video.c in function uvc_video_alloc_requests:
video->ep->mult is always equal to 0 and as a result, req_size = 0 which leads to a null pointer in uvc_video_encode_isoc or uvc_video_encode_bulk

(#side note: video->max_payload_size is always 0, therefore, even with uvc-gadget -b, uvc_video_encode_bulk is never called)

After modifying drivers/usb/gadget/function/uvc_video.c to force video->ep->mult to be equal to 1 before the call to uvc_video_encode_isoc, the module gets to the point of calling usb_ep_queue but the data is never queued and there is the following warning :

Apr 10 09:32:09 raspberrypi kernel: [  485.605711] ------------[ cut here ]------------
Apr 10 09:32:09 raspberrypi kernel: [  485.605854] WARNING: CPU: 0 PID: 899 at drivers/usb/gadget/udc/core.c:262 usb_ep_queue+0xc0/0xd4 [udc_core]
Apr 10 09:32:09 raspberrypi kernel: [  485.605861] Modules linked in: g_webcam usb_f_uvc libcomposite fuse rfcomm cmac bnep hci_uart btbcm bluetooth brcmfmac brcmutil snd_bcm2835 snd_pcm cfg80211 snd_timer snd rfkill bcm2835_gpiomem uio_pdrv_genirq uio fixed bcm2835_v4l2 v4l2_common videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_core videodev media i2c_dev dwc2 udc_core ip_tables x_tables ipv6 [last unloaded: usb_f_uvc]
Apr 10 09:32:09 raspberrypi kernel: [  485.605970] CPU: 0 PID: 899 Comm: uvc-gadget Not tainted 4.9.80+ #1098
Apr 10 09:32:09 raspberrypi kernel: [  485.605975] Hardware name: BCM2835
Apr 10 09:32:09 raspberrypi kernel: [  485.606030] [<c0016068>] (unwind_backtrace) from [<c0013c90>] (show_stack+0x20/0x24)
Apr 10 09:32:09 raspberrypi kernel: [  485.606056] [<c0013c90>] (show_stack) from [<c031ba98>] (dump_stack+0x20/0x28)
Apr 10 09:32:09 raspberrypi kernel: [  485.606082] [<c031ba98>] (dump_stack) from [<c0021cb4>] (__warn+0xe4/0x10c)
Apr 10 09:32:09 raspberrypi kernel: [  485.606101] [<c0021cb4>] (__warn) from [<c0021da8>] (warn_slowpath_null+0x30/0x38)
Apr 10 09:32:09 raspberrypi kernel: [  485.606179] [<c0021da8>] (warn_slowpath_null) from [<bf08db94>] (usb_ep_queue+0xc0/0xd4 [udc_core])
Apr 10 09:32:09 raspberrypi kernel: [  485.606363] [<bf08db94>] (usb_ep_queue [udc_core]) from [<bf4db454>] (uvcg_video_pump+0xb8/0x250 [usb_f_uvc])
Apr 10 09:32:09 raspberrypi kernel: [  485.606494] [<bf4db454>] (uvcg_video_pump [usb_f_uvc]) from [<bf4db7f4>] (uvcg_video_enable+0x208/0x26c [usb_f_uvc])
Apr 10 09:32:09 raspberrypi kernel: [  485.606595] [<bf4db7f4>] (uvcg_video_enable [usb_f_uvc]) from [<bf4daabc>] (uvc_v4l2_streamon+0x40/0x6c [usb_f_uvc])
Apr 10 09:32:09 raspberrypi kernel: [  485.606974] [<bf4daabc>] (uvc_v4l2_streamon [usb_f_uvc]) from [<bf0db838>] (v4l_streamon+0x28/0x2c [videodev])
Apr 10 09:32:09 raspberrypi kernel: [  485.607347] [<bf0db838>] (v4l_streamon [videodev]) from [<bf0dfac8>] (__video_do_ioctl+0x2a0/0x320 [videodev])
Apr 10 09:32:09 raspberrypi kernel: [  485.607716] [<bf0dfac8>] (__video_do_ioctl [videodev]) from [<bf0df4f8>] (video_usercopy+0x234/0x540 [videodev])
Apr 10 09:32:09 raspberrypi kernel: [  485.608085] [<bf0df4f8>] (video_usercopy [videodev]) from [<bf0df820>] (video_ioctl2+0x1c/0x24 [videodev])
Apr 10 09:32:09 raspberrypi kernel: [  485.608450] [<bf0df820>] (video_ioctl2 [videodev]) from [<bf0d9688>] (v4l2_ioctl+0xd4/0xec [videodev])
Apr 10 09:32:09 raspberrypi kernel: [  485.608656] [<bf0d9688>] (v4l2_ioctl [videodev]) from [<c0157a58>] (do_vfs_ioctl+0x9c/0x7d4)
Apr 10 09:32:09 raspberrypi kernel: [  485.608677] [<c0157a58>] (do_vfs_ioctl) from [<c01581d4>] (SyS_ioctl+0x44/0x6c)
Apr 10 09:32:09 raspberrypi kernel: [  485.608700] [<c01581d4>] (SyS_ioctl) from [<c000fe40>] (ret_fast_syscall+0x0/0x1c)
Apr 10 09:32:09 raspberrypi kernel: [  485.608709] ---[ end trace 12f94de20755f8c5 ]---
Apr 10 09:32:09 raspberrypi kernel: [  485.608718] Failed to queue request (-108)
Apr 10 09:32:09 raspberrypi kernel: [  485.608743] dwc2 20980000.usb: dwc2_hsotg_ep_sethalt(ep ce979c90 ep2in, 1)
Apr 10 09:32:09 raspberrypi kernel: [  485.608931] ------------[ cut here ]------------

I have no idea if the origin of the problem comes from g_webcam, usb_f_uvc or uvc-gadget.
I would be more than happy to dig further but I lack some knowledge. Any hint would be appreciated.

**Comment by kanejian** [comment]
Hi @jmfoucher,

I have a similar issue like yours, do you have the solution for the issue now?

**Comment by jmfoucher** [comment]
Unfortunately, no
